### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Laurian** [ArsalanDotMe/VideoStitch#2]
I was about just to make a similar NPM package based on the split/stitch I wrote here https://github.com/AJInteractive/palestineremix-video/blob/master/src/routes/compose.js#L31-L85 and looking for existing ones, I found yours.

I wonder what is the actual role of the `original` video in your implementation, I thought that stitching together the `clips[]` would be enough, is the `original` the first clip? 

Also, I'm not sure why do you sort the clips by `startTime` here https://github.com/ArsalanDotMe/VideoStitch/blob/master/lib/videomerge.js#L66

**Comment by ArsalanDotMe** [comment]
The project's original goal was to take an original video, lets say a music video, and replace a few scenes from the video with modified ones. The video merge function therefore takes the original video, the clips to overwrite on top of the original video and outputs the final merged video.

The library basically contains three functions. Video merge, video cut and video concatenate. Video merge I've already explained above and it basically calls video cut and concat.

What video cut does is that it takes the original video, and some splice regions. Imagine the whole original video as a long piece of bread, and the the clips parameter basically tells it what slices I want out of that. It basically applies cuts at the start and end points of each clip. 

To answer your last question, I sort the clips by startTime so that when they are concatenated together to make one long video file, they are joined in the correct order so the final output video isn't all jumbled up. 

You can use the video cut and video concat functions independently to fit your usecase. You don't have to use video merge if your usecase is different

**Comment by ArsalanDotMe** [comment]
Hey @Laurian I added some documentation about video cut and video concat. See if you find it useful.

**Comment by Laurian** [comment]
Cool, I suppose that it will even take URLs as input (as `fileName`) because FFmpeg can do that anyway.

**Comment by ArsalanDotMe** [comment]
It might. I haven't ever tested that though.

**Comment by Laurian** [comment]
heh, almost, got into this issue http://superuser.com/questions/1069556/ffmpeg-concat-demuxer-unsafe-file-name/1069569 trying a local fix in your code to see if that works

**Comment by Laurian** [comment]
OK, the concat needs to be like this `ffmpeg -f concat -safe 0 -protocol_whitelist file,http,https,tcp,tls` testing it with https://gist.github.com/Laurian/6dc4c52728e839d232189e0014d9fb5c

**Comment by Laurian** [comment]
It works with those changes, cool :)

**Comment by ArsalanDotMe** [comment]
Thanks! Never knew you could directly use video urls with ffmpeg. This could have saved me a considerable amount of time and code on my own project. Care to do a pull-request with that change?

**Comment by Laurian** [comment]
yup, I will do a pull-request ;)

**Comment by Laurian** [comment]
see #3

**Comment by Laurian** [comment]
Hmmm, so, now concat can concat via URLs, but there is no seek/duration clipping for them (nor for the original use).

**Comment by ArsalanDotMe** [comment]
What usecase are you trying exactly? You want to concat some clips but not the whole clips but just certain parts of them? 

If that's right, I think it can be handled using a combination of cut and concat but this way is going to be much more complex as you'll have to download the clips to local storage first and then define the cuts manually before sending the right cuts to concat.

**Comment by Laurian** [comment]
So, in https://gist.github.com/Laurian/6dc4c52728e839d232189e0014d9fb5c based on your documentation I hoped for the concat to work on subclips of the original files, when run it calls `ffmpeg -f concat -safe 0 -protocol_whitelist file,http,https,tcp,tls,crypto -i /var/folders/6_/f6nh8105525cwdl8kqwl_jjc0000gn/T/tmp-79931yRHwL66QPd0Q.txt -c copy /tmp/test.mp4 { async: true, silent: false }` where `/var/folders/6_/f6nh8105525cwdl8kqwl_jjc0000gn/T/tmp-79931yRHwL66QPd0Q.txt` is 

```
file http://player.vimeo.com/external/110467238.hd.mp4?s=1d8125fcb86fbc884d8e7ab2d71aa9d5
file http://player.vimeo.com/external/110467238.hd.mp4?s=1d8125fcb86fbc884d8e7ab2d71aa9d5
file http://player.vimeo.com/external/110904621.hd.mp4?s=b5055337d78a967c8e98372a11b57b0a
file http://player.vimeo.com/external/111081091.hd.mp4?s=fcf751b56cab4dc49e24efb01e8a0ae1
file http://player.vimeo.com/external/111081091.hd.mp4?s=fcf751b56cab4dc49e24efb01e8a0ae1
```

I think that will be a full concat of those sources ignoring `startTime` and `duration` I specified for each; which would require a videoCut for each clip before concat as the FFmpeg concat demuxer does not yet support subclipping http://ffmpeg-devel.ffmpeg.narkive.com/ZXy0QY9M/wip-seek-subfile-support-in-concat-demuxer

**Comment by Laurian** [comment]
Yup, for my use case I will have to cut each video (sourced by URL, that should work fine) and concat them afterwards.

**Comment by ArsalanDotMe** [comment]
Yeah sorry, the documentation was a bit misleading due to my copy-paste. As you've seen, the concat function does not infact use start and duration fields in the clips. It just takes a bunch of filenames and tries to join them together into one video file.
